kind: ReplicationController
apiVersion: v1
metadata:
  name: blue
  labels:
    app: blue
spec:
  replicas: 3
  selector:
    app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
        - name: blue
          image: public.ecr.aws/v2o3x6u2/capstone:latest
          env:
            - name: CAPSTONE_ENVIRONMENT
              value: "Blue Deployment"
          ports:
            - containerPort: 80
              name: http-server