apiVersion: v1
kind: Service
metadata:
  name: capstone-blue-green
  labels:
    app: capstone
spec:
  ports:
    - name: 80-8080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: green
  type: LoadBalancer