kind: ReplicationController
apiVersion: v1
metadata:
  name: green
  labels:
    app: green
spec:
  replicas: 0
  selector:
    app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
        - name: green
          image: public.ecr.aws/v2o3x6u2/capstone:v1
          env:
            - name: CAPSTONE_ENVIRONMENT
              value: "Green Deployment"
          ports:
            - containerPort: 80
              name: http-server